name: install-and-cache apt tools
description: 'GitHub Action to install and cache apt tools'
author: 'Office TECOLI, LLC'
branding: 
  color: 'orange'
  icon: 'plus-square'

inputs:
  tools: { required: true,  type: string }
  cache: { required: false, type: string, default: yes }
  key:   { required: false, type: string }

outputs:
  cache-hit:
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:

    - id: setup
      shell: bash
      run: |
        : setup use-apt-tools
        case "${{ inputs.cache }}" in
            yes|workflow) cache="${{ inputs.cache }}" ;;
            *)            cache=no ;;
        esac
        given_key="${{ inputs.key }}"
        tools="${{ inputs.tools }}"
        hash=$( (uname -mrsv; echo $tools) | (md5sum||md5) | awk '{print $1}' )
        key="$hash${given_key:+-$given_key}"
        [ "$cache" == 'workflow' ] && key="$key-${{ github.run_id }}-${{ github.run_attempt }}"
        cat << END
        ::set-output name=cache::$cache
        ::set-output name=archive::$HOME/apt-$hash.tz
        ::set-output name=key::$key
        END

    - id: cache
      if: steps.setup.outputs.cache != 'no'
      uses: actions/cache@v2
      with:
        path: ${{ steps.setup.outputs.archive }}
        key:  ${{ steps.setup.outputs.key }}

    - id: extract
      if: steps.setup.outputs.cache != 'no' && steps.cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        : extract
        archive="${{ steps.setup.outputs.archive }}"
        ls -l $archive
        [ -f $archive ] && sudo tar -C / -xvzf $archive

    - id: install
      if: steps.setup.outputs.cache == 'no' || steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: sudo apt-get install -y ${{ inputs.tools }}

    - id: archive
      if: steps.setup.outputs.cache != 'no' && steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        : archive
        tools="${{ inputs.tools }}"
        archive="${{ steps.setup.outputs.archive }}"
        list=/tmp/dpkg.out
        dpkg -L $tools | while read f; do [ -d "$f" ] || echo "$f"; done > $list
        tar -cvzf $archive -T $list
        ls -l $archive
